# Builds assets/world-map.js from Natural Earth's India point-of-view edition
# (ne_10m_admin_0_countries_ind.geojson), which shows Jammu and Kashmir, Ladakh
# (including Aksai Chin) and Arunachal Pradesh as part of India, as on Survey of India maps.
# Usage: python3 scripts/make-world-map.py path/to/ne_10m_admin_0_countries_ind.geojson
import json, math, sys, os

SRC = sys.argv[1]
OUT = os.path.join(os.path.dirname(__file__), '..', 'assets', 'world-map.js')

# Equal Earth projection
A1, A2, A3, A4 = 1.340264, -0.081106, 0.000893, 0.003796
M = math.sqrt(3) / 2
def proj(lon, lat):
    lam, phi = math.radians(lon), math.radians(lat)
    th = math.asin(M * math.sin(phi))
    t2, t6 = th * th, th ** 6
    x = 2 * math.sqrt(3) * lam * math.cos(th) / (3 * (9 * A4 * t6 * t2 + 7 * A3 * t6 + 3 * A2 * t2 + A1))
    y = A4 * t6 * t2 * th + A3 * t6 * th + A2 * t2 * th + A1 * th
    return x, -y

XMAX = proj(180, 0)[0]
W = 1000.0
S = W / (2 * XMAX)
def P(lon, lat):
    x, y = proj(lon, lat)
    return (x + XMAX) * S, y * S

def dp_ring(pts, tol):
    # a closed ring starts and ends on the same point, so split it at the vertex farthest from the start
    if len(pts) < 8: return pts
    x0, y0 = pts[0]
    far = max(range(len(pts)), key=lambda i: (pts[i][0] - x0) ** 2 + (pts[i][1] - y0) ** 2)
    a, b = dp(pts[:far + 1], tol), dp(pts[far:], tol)
    return a[:-1] + b

def dp(pts, tol):
    # Douglas-Peucker on an open polyline
    if len(pts) < 5: return pts
    keep = [False] * len(pts); keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        a, b = stack.pop()
        ax, ay = pts[a]; bx, by = pts[b]
        dx, dy = bx - ax, by - ay; L = math.hypot(dx, dy) or 1e-9
        best, idx = 0, -1
        for i in range(a + 1, b):
            px, py = pts[i]
            d = abs(dy * px - dx * py + bx * ay - by * ax) / L
            if d > best: best, idx = d, i
        if best > tol and idx > 0:
            keep[idx] = True; stack += [(a, idx), (idx, b)]
    return [p for p, k in zip(pts, keep) if k]

def area(r):
    return 0.5 * sum(r[i][0] * r[i - 1][1] - r[i - 1][0] * r[i][1] for i in range(len(r)))
def centroid(r):
    a = area(r) or 1e-9
    cx = sum((r[i][0] + r[i - 1][0]) * (r[i][0] * r[i - 1][1] - r[i - 1][0] * r[i][1]) for i in range(len(r))) / (6 * a)
    cy = sum((r[i][1] + r[i - 1][1]) * (r[i][0] * r[i - 1][1] - r[i - 1][0] * r[i][1]) for i in range(len(r))) / (6 * a)
    return cx, cy

TOL, MIN_AREA = 0.45, 0.6
data = json.load(open(SRC))
countries = []
ymin = 1e9
for f in data['features']:
    p = f['properties']; iso = p.get('ADM0_A3')
    if iso == 'ATA': continue
    g = f['geometry']
    polys = g['coordinates'] if g['type'] == 'MultiPolygon' else [g['coordinates']]
    rings = []
    for poly in polys:
        outer = [P(lon, lat) for lon, lat in poly[0]]
        rings.append(outer)
    rings.sort(key=lambda r: -abs(area(r)))
    out, d = [], ''
    for i, r in enumerate(rings):
        a = abs(area(r))
        if i > 0 and a < MIN_AREA: continue
        s = dp_ring(r, TOL if a > 4 else TOL * 0.5)
        if len(s) < 4:
            if i > 0: continue
            s = r
        d += 'M' + 'L'.join(f'{x:.1f} {y:.1f}' for x, y in s) + 'Z'
        ymin = min(ymin, min(y for _, y in s))
    if not d: continue
    cx, cy = centroid(rings[0])
    countries.append({'n': p.get('NAME'), 'iso': iso, 'd': d, 'cx': round(cx, 1), 'cy': round(cy, 1)})

# representative points for AIS chapters (lon, lat); IN is the arc origin
LL = {'IN': (78.9, 22.6), 'US': (-98.5, 39.5), 'MX': (-102.5, 23.6), 'AU': (134.5, -25.7), 'NZ': (172.6, -41.8), 'JP': (138.3, 36.5),
      'KR': (127.9, 36.4), 'SG': (103.82, 1.35), 'MY': (101.9, 4.0), 'AE': (54.3, 24.0), 'DE': (10.4, 51.1), 'FR': (2.4, 46.6),
      'IE': (-8.0, 53.3), 'IT': (12.6, 42.8), 'ES': (-3.7, 40.2), 'PT': (-8.2, 39.6), 'NL': (5.3, 52.2), 'BE': (4.5, 50.6),
      'CH': (8.2, 46.8), 'AT': (14.5, 47.6), 'CZ': (15.4, 49.8), 'HU': (19.4, 47.2), 'PL': (19.3, 52.0), 'CY': (33.2, 35.0),
      'LV': (24.6, 56.9), 'LT': (23.9, 55.3), 'EE': (25.0, 58.7), 'FI': (26.0, 62.5), 'SE': (15.5, 60.5), 'NO': (9.0, 61.0), 'DK': (9.5, 56.0)}
points = {k: [round(v, 1) for v in P(*ll)] for k, ll in LL.items()}

js = ('// Generated by scripts/make-world-map.py from Natural Earth 1:10m admin-0 countries, India point of view (public domain).\n'
      '// Borders follow the Government of India depiction, including Jammu and Kashmir, Ladakh and Arunachal Pradesh.\n'
      'window.WORLD=' + json.dumps({'w': W, 'source': 'Natural Earth, India point of view', 'countries': countries, 'points': points}, separators=(',', ':')) + ';\n')
open(OUT, 'w').write(js)
print('countries', len(countries), 'bytes', len(js))
